### ISSUE TITLE
using RCall gives init error: ambiguous any function

### ISSUE THREAD

**Issue by xiaojiemao** [JuliaInterop/RCall.jl#237] opened 2018-03-27 18:25 UTC
Hi, I tried the RCall package on linux server and the `using RCall` gives me the following error:

```
INFO: Precompiling module RCall.
WARNING: Method definition promote_rule(Type{T}, Type{Any}) in module Nulls at /home/xm77/.julia/v0.6/Nulls/src/Nulls.jl:29 overwritten in module Missings at /home/xm77/.julia/v0.6/Missings/src/Missings.jl:52.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/xm77/.julia/v0.6/NullableArrays/src/operators.jl:99.
INFO: Using R installation at /usr/local/R/r-3.4.4/lib/R
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/xm77/.julia/v0.6/NullableArrays/src/operators.jl:99.
WARNING: Method definition promote_rule(Type{T}, Type{Any}) in module Missings at /home/xm77/.julia/v0.6/Missings/src/Missings.jl:52 overwritten in module Nulls at /home/xm77/.julia/v0.6/Nulls/src/Nulls.jl:29.
ERROR: InitError: MethodError: any(::Base.##136#137{String}, ::Array{Any,1}) is ambiguous. Candidates:
  any(f, A::AbstractArray{#s3,N} where N where #s3>:Nulls.Null) in Nulls at /home/xm77/.julia/v0.6/Nulls/src/Nulls.jl:208
  any(f, A::AbstractArray{#s16,N} where N where #s16>:Missings.Missing) in Missings at /home/xm77/.julia/v0.6/Missings/src/Missings.jl:177
Possible fix, define
  any(::Any, ::AbstractArray{#s16,N} where N where #s16>:Union{Missings.Missing, Nulls.Null})
Stacktrace:
 [1] keymap_merge(::Dict{Char,Any}, ::Dict{Any,Any}) at ./LineEdit.jl:873
 [2] keymap_unify(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:897
 [3] keymap(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:919
 [4] setup_search_keymap(::Base.REPL.REPLHistoryProvider) at ./LineEdit.jl:1259
 [5] create_r_repl(::Base.REPL.LineEditREPL, ::Base.LineEdit.Prompt) at /home/xm77/.julia/v0.6/RCall/src/RPrompt.jl:193
 [6] repl_init(::Base.REPL.LineEditREPL) at /home/xm77/.julia/v0.6/RCall/src/RPrompt.jl:213
 [7] __init__() at /home/xm77/.julia/v0.6/RCall/src/setup.jl:243
 [8] _include_from_serialized(::String) at ./loading.jl:157
 [9] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [10] _require(::Symbol) at ./loading.jl:498
 [11] require(::Symbol) at ./loading.jl:405
during initialization of module RCall
```

I was wondering what's happening here but the package works well on my local machine with julia of the same version and R 3.4.3. I already set `ENV["R_HOME"] = /usr/local/R/r-3.4.4/lib/R` (`/usr/local/R/r-3.4.4/bin` is also on the PATH) so I think it finds the right R installation considering the INFO. The following is information for my server system, R and julia version:

```
julia --version
julia version 0.6.2
```

```
> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "4.4"

$year
[1] "2018"

$month
[1] "03"

$day
[1] "15"

$`svn rev`
[1] "74408"

$language
[1] "R"

$version.string
[1] "R version 3.4.4 (2018-03-15)"

$nickname
[1] "Someone to Lean On"

```
```
> Sys.info()
                                    sysname 
                                       "Linux" 
                                       release 
                           "4.4.0-112-generic" 
                                       version 
"#135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018" 
```

I appreciate your help very much.

**Comment by randy3k** [comment] 2018-03-27 18:55
duplicate of #225

**Closed by randy3k** 2018-03-27 18:55 UTC
