### ISSUE TITLE
initializing RCall

### ISSUE THREAD

**Issue by ignacioq** [JuliaInterop/RCall.jl#233] opened 2018-03-12 22:10 UTC
With the latest version of OSX and Julia 0.6.2 I've been getting this error when initializing RCall. If I retype `using RCall` I'm able to use it, but don't know why this error always appears. 

ERROR: InitError: MethodError: any(::Base.##136#137{String}, ::Array{Any,1}) is ambiguous. Candidates:
  any(f, A::AbstractArray{#s3,N} where N where #s3>:Nulls.Null) in Nulls at /Users/ignacioq/.julia/v0.6/Nulls/src/Nulls.jl:208
  any(f, A::AbstractArray{#s16,N} where N where #s16>:Missings.Missing) in Missings at /Users/ignacioq/.julia/v0.6/Missings/src/Missings.jl:177
Possible fix, define
  any(::Any, ::AbstractArray{#s16,N} where N where #s16>:Union{Missings.Missing, Nulls.Null})
Stacktrace:
 [1] keymap_merge(::Dict{Char,Any}, ::Dict{Any,Any}) at ./LineEdit.jl:873
 [2] keymap_unify(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:897
 [3] keymap(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:919
 [4] setup_search_keymap(::Base.REPL.REPLHistoryProvider) at ./LineEdit.jl:1259
 [5] create_r_repl(::Base.REPL.LineEditREPL, ::Base.LineEdit.Prompt) at /Users/ignacioq/.julia/v0.6/RCall/src/RPrompt.jl:193
 [6] repl_init(::Base.REPL.LineEditREPL) at /Users/ignacioq/.julia/v0.6/RCall/src/RPrompt.jl:213
 [7] __init__() at /Users/ignacioq/.julia/v0.6/RCall/src/setup.jl:243
 [8] _include_from_serialized(::String) at ./loading.jl:157
 [9] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [10] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [11] _require(::Symbol) at ./loading.jl:441
 [12] require(::Symbol) at ./loading.jl:405
 [13] _include_from_serialized(::String) at ./loading.jl:157
 [14] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [15] _require(::Symbol) at ./loading.jl:464
 [16] require(::Symbol) at ./loading.jl:405
during initialization of module RCall

Thanks!

**Comment by randy3k** [comment] 2018-03-12 22:35
Duplicate of #225, #227, #230, #232

**Closed by randy3k** 2018-03-12 22:35 UTC
