### ISSUE TITLE
InitError on using RCall

### ISSUE THREAD

**Issue by jayvn** [JuliaInterop/RCall.jl#227] opened 2018-02-22 09:23 UTC
```
julia> using RCall
WARNING: Method definition midpoints(Base.Range{T} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /home/jay/.julia/v0.6/StatsBase/src/hist.jl:535.
WARNING: Method definition midpoints(AbstractArray{T, 1} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /home/jay/.julia/v0.6/StatsBase/src/hist.jl:533.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jay/.julia/v0.6/NullableArrays/src/operators.jl:99.
WARNING: Method definition promote_rule(Type{T}, Type{Any}) in module Missings at /home/jay/.julia/v0.6/Missings/src/Missings.jl:52 overwritten in module Nulls at /home/jay/.julia/v0.6/Nulls/src/Nulls.jl:29.
ERROR: InitError: MethodError: any(::Base.##136#137{String}, ::Array{Any,1}) is ambiguous. Candidates:
  any(f, A::AbstractArray{#s3,N} where N where #s3>:Nulls.Null) in Nulls at /home/jay/.julia/v0.6/Nulls/src/Nulls.jl:208
  any(f, A::AbstractArray{#s16,N} where N where #s16>:Missings.Missing) in Missings at /home/jay/.julia/v0.6/Missings/src/Missings.jl:177
Possible fix, define
  any(::Any, ::AbstractArray{#s16,N} where N where #s16>:Union{Missings.Missing, Nulls.Null})
Stacktrace:
 [1] keymap_merge(::Dict{Char,Any}, ::Dict{Any,Any}) at ./LineEdit.jl:873
 [2] keymap_unify(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:897
 [3] keymap(::Array{Dict{Any,Any},1}) at ./LineEdit.jl:919
 [4] setup_search_keymap(::Base.REPL.REPLHistoryProvider) at ./LineEdit.jl:1259
 [5] create_r_repl(::Base.REPL.LineEditREPL, ::Base.LineEdit.Prompt) at /home/jay/.julia/v0.6/RCall/src/RPrompt.jl:193
 [6] repl_init(::Base.REPL.LineEditREPL) at /home/jay/.julia/v0.6/RCall/src/RPrompt.jl:213
 [7] __init__() at /home/jay/.julia/v0.6/RCall/src/setup.jl:243
 [8] _include_from_serialized(::String) at ./loading.jl:157
 [9] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [10] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [11] _require(::Symbol) at ./loading.jl:441
 [12] require(::Symbol) at ./loading.jl:405
during initialization of module RCall
```
Used the latest version by doing 'Pkg.update()`
This makes RCall unusable for me.
```
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> Pkg.status("RCall")
 - RCall                         0.8.1
```

**Comment by nalimilan** [comment] 2018-02-22 12:14
Duplicate of https://github.com/JuliaInterop/RCall.jl/issues/225.

**Closed by nalimilan** 2018-02-22 12:14 UTC
