### ISSUE TITLE
Seg fault when operating on same data but transferred from julia

### ISSUE THREAD

**Issue by Ward9250** [JuliaInterop/RCall.jl#196] opened 2017-07-05 19:43 UTC
Hi

I can use RCall to load data in R and call the `pratchet` function on it to compute a phylogeny.

```julia
julia> using BioSequences
julia> using RCall
julia> using BioBridgeR.APE

julia> function do_r()
           R"""
           library(ape)
           library(phangorn)
           library(seqinr)

           data(woodmouse)

           md <- as.phyDat(woodmouse)
           pratchet(md)
           """
       end
do_r (generic function with 1 method)

julia> do_r()
WARNING: RCall.jl: 
Attaching package: ‘seqinr’

The following objects are masked from ‘package:ape’:

    as.alignment, consensus

[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
[1] "Best pscore so far: 68"
RCall.RObject{RCall.VecSxp}

Phylogenetic tree with 15 tips and 13 internal nodes.

Tip labels:
	No305, No304, No306, No0906S, No0908S, No0909S, ...

Unrooted; no branch lengths.
```

Yet, if I do the exact same thing, but instead the very same data comes from julia, I get a segfault:

```julia
julia> function do_r2(seqs)
           @rput seqs

           R"""
           ms <- as.phyDat(seqs)
           pratchet(ms)
           """
       end
do_r2 (generic function with 1 method)

julia> do_r2(@rget woodmouse)

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
sankoffTips at /private/tmp/Rtmpfkn3iJ/R.INSTALL161cc1da07383/phangorn/src/sankoff.c:144 [inlined]
sankoff3B at /private/tmp/Rtmpfkn3iJ/R.INSTALL161cc1da07383/phangorn/src/sankoff.c:173
R_doDotCall at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/dotcode.c:623
do_dotcall at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/dotcode.c:1251
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5658
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:732
protectedEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:763
R_ToplevelExec at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:718
R_tryEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:777
#74 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:43
disable_sigint at ./c.jl:323 [inlined]
tryEval at /Users/bward/.julia/v0.6/RCall/src/eval.jl:39 [inlined]
#reval_p#76 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:54
unknown function (ip: 0x118dc110c)
#reval_p at ./<missing>:0
unknown function (ip: 0x118dbd783)
#reval_p#77 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:74
unknown function (ip: 0x118dc88dc)
#reval_p at ./<missing>:0
unknown function (ip: 0x118dc8443)
macro expansion at /Users/bward/.julia/v0.6/RCall/src/macros.jl:68 [inlined]
do_r2 at ./REPL[6]:4
unknown function (ip: 0x118e134d2)
do_call at /Users/bward/github/julia/src/interpreter.c:75
eval at /Users/bward/github/julia/src/interpreter.c:242
eval_body at /Users/bward/github/julia/src/interpreter.c:539
jl_interpret_toplevel_thunk at /Users/bward/github/julia/src/interpreter.c:692
jl_toplevel_eval_flex at /Users/bward/github/julia/src/toplevel.c:592
jl_toplevel_eval_in at /Users/bward/github/julia/src/builtins.c:496
eval at ./boot.jl:235
jlcall_eval_17951 at /Users/bward/github/julia/usr/lib/julia/sys.dylib (unknown line)
eval_user_input at ./REPL.jl:66
jlcall_eval_user_input_20239 at /Users/bward/github/julia/usr/lib/julia/sys.dylib (unknown line)
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x118dac77f)
jl_apply at /Users/bward/github/julia/src/./julia.h:1424 [inlined]
start_task at /Users/bward/github/julia/src/task.c:267
Allocations: 9167457 (Pool: 9165728; Big: 1729); GC: 14
Segmentation fault: 11
```

I've tried this several ways, in several iterations. Yet it seems whenever the data comes in from julia, pratchet causes a crash. Even when the data has been transferred correctly - I know it has from my BioBridgeR unit tests and manually verifying that `woodmouse` and `seqs` are the same on the R side.

**Comment by Ward9250** [comment] 2017-07-05 20:55
Interestingly, the following works:

```julia
function do_r()
    R"""
    library(ape)
    library(phangorn)
    library(seqinr)

    data(woodmouse)

    dist.dna(woodmouse)
    """
end

function do_r2(seqs)
    @rput seqs
    R"""
    dist.dna(seqs)
    """
end

do_r()
do_r2(@rget woodmouse)
```

**Comment by randy3k** [comment] 2017-07-05 21:52
`@rput` and `@rget` are designed to work in REPL. There might be issues if it is nested inside a function. Try `globalEnv[:foo] = foo` instead.

**Comment by Ward9250** [comment] 2017-07-05 23:36
It still seems to have issues:

```julia
using BioSequences, RCall, BioBridgeR

function prepare_r2(seq::Vector{DNASequence}, seed::Int)
    globalEnv[:SEQUENCES] = seq
    globalEnv[:seed] = seed
    R"""
    library(ape)
    library(phangorn)
    library(seqinr)
    set.seed(seed)
    pd <- as.phyDat(SEQUENCES)
    PHYLOGENY <- pratchet(pd, trace = 0)
    """
end

s = collect(sequence(i) for i in FASTA.Reader(open("Desktop/Johanna_PINNS/data/Chromosome1_CD_Concat.fas", "r")))

 prepare_r2(s, 5)

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
sankoffTips at /private/tmp/Rtmpfkn3iJ/R.INSTALL161cc1da07383/phangorn/src/sankoff.c:144 [inlined]
sankoff3B at /private/tmp/Rtmpfkn3iJ/R.INSTALL161cc1da07383/phangorn/src/sankoff.c:173
R_doDotCall at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/dotcode.c:623
do_dotcall at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/dotcode.c:1251
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5658
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
bcEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:5630
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:616
Rf_applyClosure at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:1135
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:732
do_set at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:2197
Rf_eval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/eval.c:685
protectedEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:763
R_ToplevelExec at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:718
R_tryEval at /Builds/R-builds/nightly/mavericks-x86_64/R-3.3.2/src/main/../../../../R-3.3.2/src/main/context.c:777
#74 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:43
disable_sigint at ./c.jl:323 [inlined]
tryEval at /Users/bward/.julia/v0.6/RCall/src/eval.jl:39 [inlined]
#reval_p#76 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:54
unknown function (ip: 0x11856714c)
#reval_p at ./<missing>:0
unknown function (ip: 0x1185637a3)
#reval_p#77 at /Users/bward/.julia/v0.6/RCall/src/eval.jl:74
unknown function (ip: 0x11856e91c)
#reval_p at ./<missing>:0
unknown function (ip: 0x11856e483)
macro expansion at /Users/bward/.julia/v0.6/RCall/src/macros.jl:72 [inlined]
prepare_r2 at ./REPL[4]:4
unknown function (ip: 0x1185c25b9)
do_call at /Users/bward/github/julia/src/interpreter.c:75
eval at /Users/bward/github/julia/src/interpreter.c:242
jl_interpret_toplevel_expr at /Users/bward/github/julia/src/interpreter.c:34
jl_toplevel_eval_flex at /Users/bward/github/julia/src/toplevel.c:577
jl_toplevel_eval_in at /Users/bward/github/julia/src/builtins.c:496
eval at ./boot.jl:235
jlcall_eval_17951 at /Users/bward/github/julia/usr/lib/julia/sys.dylib (unknown line)
eval_user_input at ./REPL.jl:66
jlcall_eval_user_input_20239 at /Users/bward/github/julia/usr/lib/julia/sys.dylib (unknown line)
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x11855276f)
jl_apply at /Users/bward/github/julia/src/./julia.h:1424 [inlined]
start_task at /Users/bward/github/julia/src/task.c:267
Allocations: 21362281 (Pool: 21360466; Big: 1815); GC: 56
Segmentation fault: 11
```

**Comment by randy3k** [comment] 2017-07-06 05:13
What if you run
```
    globalEnv[:SEQUENCES] = seq
    globalEnv[:seed] = seed
```
outside of the function?

The segfault comes form this [line](https://github.com/KlausVigo/phangorn/blob/b0f92c98eaa84fc6e5ae730c285be8e7dc010368/src/sankoff.c#L144) or the R package `phangorn`. It may be an issue of `phangorn`, perhaps missing `protect` to a SEXP?

It will be great if you can provide me a reproducible example on this matter.

**Comment by Ward9250** [comment] 2017-07-06 10:15
```julia
using BioSequences
using RCall
using BioBridgeR.APE

seed = 5


R"""
library(ape)
library(phangorn)
library(seqinr)

set.seed($seed)

data(woodmouse)
"""

# woodmouse contains sequence data in R.
# using it works fine:
R"""
acctran(pratchet(as.phyDat(woodmouse), trace = 0), as.phyDat(woodmouse))
"""

println("woodmouse in R works")

# However if the same data came from julia, it does not work:

 @rget woodmouse

 juliaseqs = copy(woodmouse)

 globalEnv[:jlseqs] = juliaseqs

 R"""
 acctran(pratchet(as.phyDat(jlseqs), trace = 0), as.phyDat(jlseqs))
 """

println("same data transferred from julia works")
```

This example is reproducible if you have R with ape, phangorn, and seqinr packages installed, and BioBridgeR release v0.1.0 which got merged to METADATA last night. 

The first pratchet call completes fine, the second one segfaults.

**Comment by randy3k** [comment] 2017-07-06 16:30
@Ward9250 

It may be due to the missing labels?

```
R> attributes(jlseqs)
$dim
[1]  15 965

$class
[1] "DNAbin"


R> attributes(woodmouse)
$dim
[1]  15 965

$dimnames
$dimnames[[1]]
 [1] "No305"   "No304"   "No306"   "No0906S" "No0908S" "No0909S" "No0910S"
 [8] "No0912S" "No0913S" "No1103S" "No1007S" "No1114S" "No1202S" "No1206S"
[15] "No1208S"

$dimnames[[2]]
NULL


$class
[1] "DNAbin"

```

**Comment by randy3k** [comment] 2017-07-12 04:03
Did you fix the issue?

**Comment by Ward9250** [comment] 2017-08-02 12:57
@randy3k You are absolutely correct, this is the result of the missing labels!

**Comment by randy3k** [comment] 2017-08-15 03:22
can we close it now?

**Closed** 2017-08-15 14:40 UTC
