### ISSUE TITLE
error loading Rcall

### ISSUE THREAD

**Issue by fdennig** [JuliaInterop/RCall.jl#248] opened 2018-07-22 15:36 UTC
Hi guys, I get the following error when calling "using RCall":

ERROR: InitError: MethodError: any(::Base.##136#137{String}, ::Array{Any,1}) is ambiguous. Candidates:
  any(f, A::AbstractArray{#s16,N} where N where #s16>:Missings.Missing) in Missings at C:\Users\fdennig\.julia\v0.6\Missings\src\Missings.jl:177
  any(f, A::AbstractArray{#s3,N} where N where #s3>:Nulls.Null) in Nulls at C:\Users\fdennig\.julia\v0.6\Nulls\src\Nulls.jl:208
Possible fix, define
  any(::Any, ::AbstractArray{#s3,N} where N where #s3>:Union{Missings.Missing, Nulls.Null})

Furthermore, even though i have julia v0.6 loaded, RCall only Pkg.add("RCall") only installs RCall v 0.8.1
So it seems i am not able to install the latest version, and, furthermore, I can't even load the package. Could someone please point me in the possible direction of a solution to this?

thanks!

**Comment by randy3k** [comment] 2018-07-22 17:33
Possible duplicate of #225, #227, #230, #232

**Closed** 2022-10-19 00:00 UTC
